name: Keep Supabase Awake (Daily)

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar fecha actual
        run: date

      - name: Ping Supabase
        run: |
          echo "Haciendo ping a Supabase..."
          curl -s "${{ secrets.SUPABASE_URL }}/rest/v1/" \
            -H "apikey: ${{ secrets.SUPABASE_API_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_API_KEY }}"
          echo "✅ Ping completado correctamente"

